### ISSUE TITLE
Prevent Black screen flicker after video plays?

### ISSUE THREAD

**Issue by elbombillopublic** [huceke/omxplayer#133]
This wasn't noticible before when on full screen play, now that I'm using "--win" flag and using a much smaller video box. I'm playing multiple videos in a loop but it flickers the entire screen after each video.

**Comment by skgsergio** [comment]
I'm sure you are using my builds (http://omxplayer.sconde.net/) and that's caused by my omxplayer launch script.

To be exact the problem you have is the part I made as a hack to avoid black screens after playback problem (#44 and #63).

As I can't find a better way to fix, and I found mine too ugly, I didn't made a pull request. Here is my current script: https://gist.github.com/skgsergio/0e7144680ab5b0d41e5d

If anyone has a better idea to fix #44, #63 and this issue together is welcome.

**Comment by elbombillopublic** [comment]
This is very novice question...Can that "Fix" be disabled easly? I plan to have omxplayer running 24/7 looping through videos in a folder (also have to make sure this will work). I wouldn't mind if the screen blanks out in the smaller window but not he entire screen.

**Comment by skgsergio** [comment]
You can edit /usr/local/omxplayer and remove everything since line 13 (GREP=`which grep`)

**Comment by elbombillopublic** [comment]
It actually works perfectly, I've had a video loop running for over 6 hours and since it's not full screen just a small 640x480 when it goest to next video the entire screen DOESN'T flicker :) Thanks for a great project.
