### ISSUE TITLE
Automatic aspect ratio of HDMI /w Touchscreen

### ISSUE THREAD

**Issue by gtrawoger** [huceke/omxplayer#255]
I have a Raspberry Pi 2 together with the new 7" touchscreen (800x480 - 5:3 ratio) that connects over the DSI port. I also have a 1080P screen attached to the HDMI port of the Pi.

_Here is what I have discovered:_

When I use the `--output=5` to play the video over the HDMI, while having the GUI (python, tkinter) on the touchscreen, it plays the video in the wrong aspect ratio (squished top and bottom, with black bars) even though the video is properly formatted to 16:9.

If I add `--win 0,0,1919,1079` to the video it works as intended. 

_My issue:_

I would like omxplayer to automatically detect the aspect ratio properly of the output device, without having to define the `--win` parameter. It seems to be taking the touchscreen's aspect ratio, instead of the HDMI screen.

The issue is that I sometimes have a 720P screen, other times a 1080P screen to use. Every time this happens, I need to fix my code.

**Comment by jehutting** [comment]
This repository is _supposed to be_ a dead repository.
Latest/active omxplayer development happens at [popcornmix omxplayer](https://github.com/popcornmix/omxplayer). This issue is better of there, as it is popcornmix's omxplayer which has the **--display** option supported.
Although... popcornmix still keeps looking after the not this repository related issues :-)

**Comment by popcornmix** [comment]
Yes, can you create the issue at https://github.com/popcornmix/omxplayer as this repo is dead.

**Comment by darconeous** [comment]
Is there a link to the real bug tracking this?
