### ISSUE TITLE
Allow '=' to increase audio volume

### ISSUE THREAD

**Issue by ToadKing** [huceke/omxplayer#32]
My keyboard doesn't have a numpad, and using Shift + = does not work to increase volume. Can you make both + and = increase the volume?

**Comment by ph0ng** [comment]
That would make little sense for keyboard layouts where = is not adjacent to -. For example, my Swedish PC-105 keyboard has + to the right of =, meaning that I would like = to decrease volume! 

Perhaps a pair of unused alphanumeric keys can be spared instead (assuming qwerty layout is considered standard).

**Comment by GriffenJBS** [comment]
Rather than using a pair of keys I always liked the idea that V was volume and shift determined if it was up or down, so "v" make the volume go down, "V" makes it go up, it saves keys on the keyboard and gives larger dead spaces so you don't have the "what did I just bump" effect.

Ideally the key mapping could be displayed from the CLI and the key map settings would be stored in ~/.omxplayer, but those are different issues themselves.

**Comment by popcornmix** [comment]
Added with https://github.com/huceke/omxplayer/commit/c2df34762babea5f0ff99529fad555720a92ec80.
